version: "3"

services:
  nginx:
    build:
      context: ./nginx
    networks:
      - node-network
    ports:
      - "8080:8080"
    depends_on:
      - node

  node:
    build:
      context: ./node
    restart: always
    tty: true
    networks:
      - node-network
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./db/mysql:/var/lib/mysql
      - ./db/mysql-init:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
